import { it } from 'vitest'
import { fireEvent, render } from '@testing-library/react'
import { Event } from 'examples/Event'

it('Event', async () => {
  const { findByText, getByText, unmount } = render(<Event />)

  fireEvent.click(getByText('Get Times'))
  await findByText('Parent Channel: 0')
  await findByText('SiblingOne Channel: 0')
  await findByText('SiblingTwo Channel: 0')
  await findByText('Parent Receiving Times: 1 2')
  await findByText('SiblingOne Receiving Times: 1 2')
  await findByText('SiblingTwo Receiving Times: 1 2')
  fireEvent.click(getByText('Parent + 1'))
  fireEvent.click(getByText('Get Times'))
  await findByText('Parent Channel: 1')
  await findByText('SiblingOne Channel: 1')
  await findByText('SiblingTwo Channel: 1')
  await findByText('Parent Receiving Times: 2 4')
  await findByText('SiblingOne Receiving Times: 2 4')
  await findByText('SiblingTwo Receiving Times: 2 4')
  fireEvent.click(getByText('SiblingOne + 1'))
  fireEvent.click(getByText('Get Times'))
  await findByText('Parent Channel: 2')
  await findByText('SiblingOne Channel: 2')
  await findByText('SiblingTwo Channel: 2')
  await findByText('Parent Receiving Times: 3 6')
  await findByText('SiblingOne Receiving Times: 3 6')
  await findByText('SiblingTwo Receiving Times: 3 6')
  fireEvent.click(getByText('SiblingTwo + 1'))
  fireEvent.click(getByText('Get Times'))
  await findByText('Parent Channel: 3')
  await findByText('SiblingOne Channel: 3')
  await findByText('SiblingTwo Channel: 3')
  await findByText('Parent Receiving Times: 4 8')
  await findByText('SiblingOne Receiving Times: 4 8')
  await findByText('SiblingTwo Receiving Times: 4 8')
  unmount()
})
