import { it } from 'vitest'
import { fireEvent, render } from '@testing-library/react'
import { Starter } from 'examples/Starter'

it('Starter', async () => {
  const { findByText, getByTestId, unmount } = render(<Starter />)

  await findByText('Starter count: 0')
  await findByText('Starter privateCount: 0')
  await findByText('Starter value: 0')
  await findByText('Starter valueProp: 0')
  await findByText('Counter count: 0')
  await findByText('Counter value: 0')
  await findByText('Counter privateValue: 0')
  await findByText('Counter valueProp: 0')

  fireEvent.click(getByTestId('Starter:setValueProp'))
  await findByText('Starter count: 0')
  await findByText('Starter privateCount: 0')
  await findByText('Starter value: 0')
  await findByText('Starter valueProp: 1')
  await findByText('Counter count: 0')
  await findByText('Counter value: 0')
  await findByText('Counter privateValue: 0')
  await findByText('Counter valueProp: 1')

  fireEvent.click(getByTestId('Counter:setValueProp'))
  await findByText('Starter count: 0')
  await findByText('Starter privateCount: 0')
  await findByText('Starter value: 0')
  await findByText('Starter valueProp: 1')
  await findByText('Counter count: 0')
  await findByText('Counter value: 0')
  await findByText('Counter privateValue: 0')
  await findByText('Counter valueProp: 2')

  fireEvent.click(getByTestId('Starter:setCount'))
  await findByText('Starter count: 1')
  await findByText('Starter privateCount: 1')
  await findByText('Starter value: 0')
  await findByText('Starter valueProp: 1')
  await findByText('Counter count: 1')
  await findByText('Counter value: 0')
  await findByText('Counter privateValue: 0')
  await findByText('Counter valueProp: 2')

  fireEvent.click(getByTestId('Starter:setCountPrivately'))
  await findByText('Starter count: 1')
  await findByText('Starter privateCount: 2')
  await findByText('Starter value: 0')
  await findByText('Starter valueProp: 1')
  await findByText('Counter count: 1')
  await findByText('Counter value: 0')
  await findByText('Counter privateValue: 0')
  await findByText('Counter valueProp: 2')

  fireEvent.click(getByTestId('Starter:setValue'))
  await findByText('Starter count: 1')
  await findByText('Starter privateCount: 2')
  await findByText('Starter value: 1')
  await findByText('Starter valueProp: 1')
  await findByText('Counter count: 1')
  await findByText('Counter value: 1')
  await findByText('Counter privateValue: 1')
  await findByText('Counter valueProp: 2')

  fireEvent.click(getByTestId('Counter:setValue'))
  await findByText('Starter count: 1')
  await findByText('Starter privateCount: 2')
  await findByText('Starter value: 1')
  await findByText('Starter valueProp: 1')
  await findByText('Counter count: 1')
  await findByText('Counter value: 1')
  await findByText('Counter privateValue: 2')
  await findByText('Counter valueProp: 2')
  unmount()
})
