import { it } from 'vitest'
import { fireEvent, render } from '@testing-library/react'
import { ConnectValtio } from 'examples/Valtio'

it('Valtio', async () => {
  const { findByText, getByText, unmount } = render(<ConnectValtio />)

  await findByText('Parent Channel: 0')
  await findByText('Channel Value: 0')
  await findByText('Store: 0')
  await findByText('Store Value: 0')
  await findByText('Channel: 0')
  await findByText('GC Channel: 0')
  await findByText('Listeners: 1')
  fireEvent.click(getByText('Store + 1'))
  await findByText('Parent Channel: 1')
  await findByText('Channel Value: 0')
  await findByText('Store: 1')
  await findByText('Store Value: 0')
  await findByText('Channel: 1')
  await findByText('GC Channel: 1')
  await findByText('Listeners: 1')
  fireEvent.click(getByText('Channel + 1'))
  await findByText('Parent Channel: 2')
  await findByText('Channel Value: 0')
  await findByText('Store: 2')
  await findByText('Store Value: 0')
  await findByText('Channel: 2')
  await findByText('GC Channel: 2')
  await findByText('Listeners: 1')
  fireEvent.click(getByText('Channel Value + 1'))
  await findByText('Parent Channel: 2')
  await findByText('Channel Value: 1')
  await findByText('Store: 2')
  await findByText('Store Value: 1')
  await findByText('Channel: 2')
  await findByText('GC Channel: 2')
  await findByText('Listeners: 1')
  fireEvent.click(getByText('Store Value + 1'))
  await findByText('Parent Channel: 2')
  await findByText('Channel Value: 2')
  await findByText('Store: 2')
  await findByText('Store Value: 2')
  await findByText('Channel: 2')
  await findByText('GC Channel: 2')
  await findByText('Listeners: 1')
  unmount()
})
